### ISSUE TITLE
READ ME

### ISSUE THREAD

**Issue by timeyers** [extatent/PhoenixGrabber#1]
Why is there no instructions on how to compile this?
A little bit of info in the read me file would have been very helpful

**Comment by LolekLiam** [comment]
download source code, open the .sln file and press ctrl+b

**Comment by LolekLiam** [comment]
also u need visual studio to do this

**Comment by LolekLiam** [comment]
also this is just an exe maker for the actual grabber. i will put the source code of the actual grabber in my github as a new repository

**Comment by LolekLiam** [comment]
@timeyers here you go https://github.com/LolekLiam/Discord-Grabber
