### ISSUE TITLE
WARNING: SCAM! MINES CRYPTO!!!

### ISSUE THREAD

**Issue by BossFlea** [extatent/PhoenixGrabber#3]
Look at the resources folder, has tools for crypto mining!

**Comment by extatent** [comment]
To be clear, [Bouncy Castle](https://www.bouncycastle.org/) is an [open source](https://github.com/bcgit/bc-csharp)  [cryptography](https://en.wikipedia.org/wiki/Cryptography) [API](https://en.wikipedia.org/wiki/Application_Programming_Interface). Crypto in BouncyCastle.Crypto.dll stands for [cryptography](https://en.wikipedia.org/wiki/Cryptography). It has nothing to do with [cryptocurrency mining](https://en.wikipedia.org/wiki/Cryptocurrency#Mining).
