### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by EgemenEditsz** [extatent/PhoenixGrabber#7]
I TRIED MY SELF AND I CANT OPEN DISCORD

**Comment by extatent** [comment]
Modify the hosts. Locate to C:\Windows\System32\drivers\etc\hosts
Remove the Discord blocking lines:
`0.0.0.0 discord.com`
`0.0.0.0 support.discord.com`
`0.0.0.0 canary.discord.com`
`0.0.0.0 ptb.discord.com`
Save. You may need to grant yourself administrator permissions.
